name: NLOS-R2
model_type: sefeature_cls
num_threads: 4
print_freq: 1000  # unit: iter
manual_seed: 200
deterministic: true

# data and augmentation
data:
  hq_path: data/hq
  lq_path: data/lq

# network specs
network_sr:
  name: swinir
  img_size: 64
  patch_size: 1
  in_chans: 3
  embed_dim: 180
  depths: [6, 6, 6, 6, 6, 6, 6, 6]
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
  window_size: 8
  mlp_ratio: 2
  upscale: 8
  img_range: 1.0
  upsampler: nearest+conv
  resi_connection: '1conv'
  unshuffle: True
  unshuffle_scale: 8
network_cls_sr:
  name: ResNet18
  num_classes: 42
network_cls_lr:
  name: ResNet18
  num_classes: 42

# path for pretrained model
path:
  network_sr: experiments/codeformer_swinir.ckpt
  network_cls_sr: IMAGENET1K_V1
  network_cls_lr: IMAGENET1K_V1
  strict_load: false

# training config
train:  
  batch_size: 32  # 4090
  epoch: 20
  save_freq: 5  # unit: epoch
  eval_freq: 1
  warmup_epoch: 16

  # optimizer
  optim_sr:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]
  optim_cls:
    type: SGD
    lr: !!float 3e-2
    momentum: 0.9
    weight_decay: !!float 1e-4
    
  # scheduler
  scheduler_sr:
    type: CosineAnnealingRestartLR
    periods: [20]
    restart_weights: [1]
    eta_min: !!float 1e-6
  scheduler_cls:
    type: CosineAnnealingRestartLR
    periods: [20]
    restart_weights: [1]
    eta_min: !!float 1e-4

  # phase1 losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1.0
    reduction: mean
  tdp_opt:
    type: CELoss
    label_smoothing: 0.0
    loss_weight: !!float 1.0

  # phase2 losses
  ce_opt:
    type: CELoss
    label_smoothing: 0.0
    loss_weight: !!float 1.0

# testing config
test:  
  batch_size: 32  # 4090
